# Created with YamlCreate.ps1 v2.2.8 $debug=NVS0.CRLF.7-3-5.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: esnet.iperf
PackageVersion: "3.14"
PackageLocale: en-US
Publisher: ESnet
PublisherUrl: https://github.com/esnet
PublisherSupportUrl: https://github.com/esnet/iperf/issues
PrivacyUrl: https://www.es.net/about/governance/data-privacy-policy/
# Author:
PackageName: iperf
PackageUrl: https://software.es.net/iperf/
License: three-clause BSD license
LicenseUrl: https://github.com/esnet/iperf/blob/master/LICENSE
Copyright: The Regents of the University of California, through Lawrence Berkeley National Laboratory
CopyrightUrl: https://github.com/esnet/iperf/#copyright
ShortDescription: iperf3, a TCP, UDP, and SCTP network bandwidth measurement tool
Description: The iperf series of tools perform active measurements to determine the maximum achievable bandwidth on IP networks. It supports tuning of various parameters related to timing, protocols, and buffers. For each test it reports the measured throughput, loss, and other parameters.
Moniker: iperf
Tags:
- iperf
- sctp
- tcp
- udp
# ReleaseNotes:
ReleaseNotesUrl: https://software.es.net/iperf/news.html#iperf-3-14-released
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.4.0
